### ISSUE TITLE
日次で料金レポートをslackに通知する

### ISSUE THREAD

**Issue by Shitomo** [morning-night-guild/platform#112]

**Comment by takokun778** [comment]
この機能はGitHubActionsで実装？
それともGCP上になにか作る？

**Comment by Shitomo** [comment]
> この機能はGitHubActionsで実装？
> それともGCP上になにか作る？

そこらへんも含めて検討＆調査中  
可能であればGitHubActionsで実装したいなと思っている

**Comment by takokun778** [comment]
一旦閉じる
