### ISSUE TITLE
プレビュー環境ではモックサーバーを参照するようにする

### ISSUE THREAD

**Issue by Shitomo** [morning-night-guild/platform#98]
# 概要

フロントエンドのプルリクの動作確認を安全かつ容易にするため、プレビュー環境ではVercelに建てたモックサーバーを参照するようにする

**Comment by Shitomo** [comment]
https://stackoverflow.com/questions/72406466/launch-mock-server-on-vercel

**Comment by takokun778** [comment]
一旦閉じる
